### ISSUE TITLE
Consecutive researches lead to incorrect requests

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet-geocoder#161]
A major issue regards the possibility to run consecutive searches.
Given the following example http://jsbin.com/qowifofiye/edit?html,output to reproduce the issue follows:
- type 'na'
- highlight the first item in the list
- type enter, the map will zoom to the selected marker
- type 'ma' in the geocoder input box
- type enter (without highlighting any item in the list)
- the map will not move
According to few tests, it seems that the second request sends the following parameters:
```
returnGeometry:true
where:upper("NAME") LIKE upper('%ma%')
outSr:4326
outFields:*
objectIds:315
f:geojson
```
The objectIds parameter is wrong, beacuse 315 is the id of the first item selected in the first query.
A quick workaround seems to remove the objectIds parameter in 
https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Providers/FeatureLayer.js#L57
as for example 
`var param = query.setters['featureIds'];
    delete query.params[param];`
I haven't tested if this issue affects other providers too.

**Comment by jgravois** [comment]
i just tested locally and it appears that this was fixed by #158.

**Comment by mepdr** [comment]
Tested against master and the issue is still present. Would you double check ?

**Comment by jgravois** [comment]
my apologies.  i missed a crucial step (that you documented clearly) when i tested the other day.

i've proposed a patch based on your suggestion.  thanks for taking the time to isolate the problem, report it and troubleshoot a solution.
